// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdeLKDLJFLWnXPJIaH2knn_xgn5iQWZy4',
    appId: '1:613906785717:web:dba076001019dd739265fc',
    messagingSenderId: '613906785717',
    projectId: 'trakio-flutter',
    authDomain: 'trakio-flutter.firebaseapp.com',
    storageBucket: 'trakio-flutter.firebasestorage.app',
    measurementId: 'G-516MHNPPPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwBbPrwR4n6X1JIEBjskyFiy55pO-FvFs',
    appId: '1:613906785717:android:193dee7dc95facc99265fc',
    messagingSenderId: '613906785717',
    projectId: 'trakio-flutter',
    storageBucket: 'trakio-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLrcUHW-VDNSiL0lwqKZDuCyHoVMF9U6U',
    appId: '1:613906785717:ios:c6193d54795f04ac9265fc',
    messagingSenderId: '613906785717',
    projectId: 'trakio-flutter',
    storageBucket: 'trakio-flutter.firebasestorage.app',
    iosBundleId: 'com.example.trakio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLrcUHW-VDNSiL0lwqKZDuCyHoVMF9U6U',
    appId: '1:613906785717:ios:c6193d54795f04ac9265fc',
    messagingSenderId: '613906785717',
    projectId: 'trakio-flutter',
    storageBucket: 'trakio-flutter.firebasestorage.app',
    iosBundleId: 'com.example.trakio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdeLKDLJFLWnXPJIaH2knn_xgn5iQWZy4',
    appId: '1:613906785717:web:930390d919ecdc8a9265fc',
    messagingSenderId: '613906785717',
    projectId: 'trakio-flutter',
    authDomain: 'trakio-flutter.firebaseapp.com',
    storageBucket: 'trakio-flutter.firebasestorage.app',
    measurementId: 'G-0778YFWTL4',
  );
}
